(setq solar-n-hemi-seasons
      '("Frühling" "Sommer" "Herbst" "Winter"))
(setq general-holidays
      '((holiday-fixed 1 1 "Neujahr")
        (holiday-fixed 5 1 "1. Mai")
        (holiday-fixed 10 12 "El Pilar")
        (holiday-fixed 12 6 "Dia de la Constitución")
        (holiday-fixed 10 31 "Reformationstag")
        ;(holiday-fixed 10 3 "Wiedervereinigung")
	; cogidas de los austríacos
	(holiday-fixed 12 31 "Silvester")
	(holiday-fixed 1 1 "Neujahr")
	(holiday-fixed 1 6 "Heilige drei Könige")
	(holiday-fixed 5 1 "Staatsfeiertag")
	(holiday-fixed 6 21 "Fête de la musique")
	(holiday-fixed 8 15 "Mariä Himmelfahrt")
	(holiday-fixed 10 26 "Nationalfeiertag")
	(holiday-fixed 11 1 "Allerheiligen")
	(holiday-fixed 12 8 "Mariä Empfängnis")
	))
(setq christian-holidays
      '((holiday-fixed 12 25 "Navidad")
        (holiday-fixed 1 6 "Reyes Magos")
        ;; Date of Easter calculation taken from holidays.el.
        (let* ((century (1+ (/ displayed-year 100)))
               (shifted-epact (% (+ 14 (* 11 (% displayed-year 19))
                                    (- (/ (* 3 century) 4))
                                    (/ (+ 5 (* 8 century)) 25)
                                    (* 30 century))
                                 30))
               (adjusted-epact (if (or (= shifted-epact 0)
                                       (and (= shifted-epact 1)
                                            (< 10 (% displayed-year 19))))
                                   (1+ shifted-epact)
                                 shifted-epact))
               (paschal-moon (- (calendar-absolute-from-gregorian
                                 (list 4 19 displayed-year))
                                adjusted-epact))
               (easter (calendar-dayname-on-or-before 0 (+ paschal-moon 7))))
          (filter-visible-calendar-holidays
           (mapcar
            (lambda (l)
              (list (calendar-gregorian-from-absolute (+ easter (car l)))
                    (nth 1 l)))
            '(
              ;;(-48 "Rosenmontag")
              ( -2 "Viernes Santo")
              (  0 "Domingo de Resurrección")
              ( +1 "Lunes de Pascua")
              ( +50 "Pentecostés")))))
        (holiday-fixed 12 8 "La Inmaculada")
        (holiday-fixed 11 1 "Todos los Santos")
        (holiday-fixed 3 19 "San José")
	; de los austríacos
	(holiday-easter-etc -48 "Rosenmontag")
        (holiday-easter-etc -47 "Faschingsdienstag")
        (holiday-easter-etc -46 "Aschermittwoch")
	(holiday-easter-etc -7 "Palmsonntag")
	(holiday-easter-etc -3 "Gründonnerstag")
	(holiday-easter-etc -2 "Karfreitag")
	(holiday-easter-etc -1 "Karsamstag")
	(holiday-easter-etc 0 "Ostersonntag")
        (holiday-easter-etc 1 "Ostermontag")
        (holiday-easter-etc 39 "Christi Himmelfahrt")
        (holiday-easter-etc 49 "Pfingstsonntag")
        (holiday-easter-etc 50 "Pfingstmontag")
        (holiday-easter-etc 60 "Fronleichnam")
	;;
;        (holiday-fixed 7 25 "Santiago")
;	(holiday-fixed 7 31 "San Ignacio")
	(holiday-fixed 8 15 "Asunción de la Virgen")))
(setq calendar-holidays
      (append general-holidays christian-holidays))

(setq local-holidays christian-holidays)

